language: java

matrix:
  include:
    - jdk: oraclejdk8
      env:
        - INTEGRATION_TEST="integration"
        - JDK=oraclejdk8
        - OS=linux
      sudo: true
      dist: trusty
      services:
        - docker
      addons:
        sonarqube:
          organization: nlesc
      os: linux
    - os: osx
      env:
        - INTEGRATION_TEST="livelocal"
        - JDK=oraclejdk8
        - OS=osx
      osx_image: xcode9
  fast_finish: true

before_install:
  - docker-compose --version;

install:
  - ./gradlew assemble

script:
  - if [ $INTEGRATION_TEST == "integration" ]; then
    ./gradlew check
    ./src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh;
    elif [ $INTEGRATION_TEST == "livelocal" ]; then
    ./src/liveTest/resources/scripts/create_symlinks;
    ./gradlew test liveTest -Dxenon.scheduler=local -Dxenon.filesystem=file -Dxenon.location=/ -Dxenon.username=$USERNAME -Dxenon.basedir=$PWD
    fi

after_script:
  - ./gradlew jacocoTestReport;
  - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
  - if [ $INTEGRATION_TEST == "integration" ]; then
    ./gradlew jacocoIntegrationTestReport jacocoFixedClientEnvironmentTestReport;
    bash <(curl -s https://codecov.io/bash) -e JDK,OS -F integration -f build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml;
    bash <(curl -s https://codecov.io/bash) -e JDK,OS -F fixedclientenvironment -f build/reports/jacoco/jacocoFixedClientEnvironmentTestReport/jacocoFixedClientEnvironmentTestReport.xml;
    sonar-scanner -Dsonar.login=$SONAR_TOKEN;
    elif [ $INTEGRATION_TEST == "live" ]; then
    ./gradlew jacocoLiveTestReport;
    bash <(curl -s https://codecov.io/bash) -e JDK,OS -F livelocal -f build/reports/jacoco/jacocoLiveTestReport/jacocoLiveTestReport.xml;
    fi
