language: java

matrix:
  # Only do docker integration tests with Oracle JDK 7: the docker
  # tests are not affected by JDK on host system.
  include:
    - jdk: oraclejdk7
      env:
        - GRADLE_BUILD_TASKS="assemble dockerBuild"
        - GRADLE_SCRIPT_TASKS="check dockerIntegrationTest"
        - GRADLE_AFTER_SUCCESS_TASKS="jacocoTestReport coveralls"
      sudo: true
      services:
        - docker
    - jdk: openjdk7
      env:
        - GRADLE_BUILD_TASKS="assemble"
        - GRADLE_SCRIPT_TASKS="check"
      sudo: false
    - jdk: oraclejdk8
      env:
        - GRADLE_BUILD_TASKS="assemble"
        - GRADLE_SCRIPT_TASKS="check"
      sudo: false
  # Stop when one of the Java versions do not work
  fast_finish: true

# Install documentation dependencies
addons:
  apt_packages:
    - pandoc
    - texlive
    - lmodern
    - docker-engine

# Install Docker compose
before_install:
  - docker version
  - mkdir -p "$HOME/bin"
  - curl -L https://github.com/docker/compose/releases/download/1.5.0/docker-compose-`uname -s`-`uname -m` > "$HOME/bin/docker-compose"
  - chmod +x "$HOME/bin/docker-compose"
  - export PATH="$PATH:$HOME/bin"
  - touch .docker-test-cache-set

install:
  - gradle $GRADLE_BUILD_TASKS -Pdocker.uid=$UID

script:
  - gradle $GRADLE_SCRIPT_TASKS -Pdocker.uid=$UID

after_success:
  - test $GRADLE_AFTER_SUCCESS_TASKS && gradle $GRADLE_AFTER_SUCCESS_TASKS
