language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
sudo: false
cache:
  directories:
    # Include individual gradle directories
    # that don't invalidate the cache
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.7
addons:
  apt_packages:
    - pandoc
    - texlive
script: ./gradlew check -xintegrationTest
