version: '{branch}-{build}'
build_script:
  - cmd: ./gradlew.bat assemble
test_script:
  - mkdir build\integrationTest & cd build\integrationTest & src\liveTest\resources\scripts\create_symlinks.bat & cd ..\..
  - cmd: ./gradlew.bat check fixedClientEnvironmentTest -x integrationTest --tests=*local* --continue
on_finish:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - "SET JDK=oraclejdk8"
  - "SET INTEGRATION_TEST=0"
  - ./gradlew.bat jacocofixedClientEnvironmentTestReport
  - pip install codecov
  - codecov -e OS,JDK,INTEGRATION_TEST -f build/reports/jacoco/test/jacocoTestReport.xml
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      Get-ChildItem "build/test-results/" -Filter *.xml | Foreach-Object{
        (New-Object 'System.Net.WebClient').UploadFile($url, $_.FullName)
      }
  - "SET INTEGRATION_TEST=local"
  - ./gradlew.bat jacocoFixedClientEnvironmentTestReport
  - codecov -e OS,JDK,INTEGRATION_TEST -f build/reports/jacoco/jacocoFixedClientEnvironmentTest/jacocoFixedClientEnvironmentTestReport.xml
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      Get-ChildItem "build/fixedClientEnvironmentTest-results/" -Filter *.xml | Foreach-Object{
        (New-Object 'System.Net.WebClient').UploadFile($url, $_.FullName)
      }
artifacts:
  - path: build/distributions/*.zip
    name: Java archive
