version: '{branch}-{build}'
build_script:
  - cmd: ./gradlew.bat assemble
test_script:
  - cmd: ./gradlew.bat check
on_finish:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - "SET JDK=oraclejdk7"
  - ./gradlew.bat jacocoTestReport
  - pip install codecov
  - codecov -e OS -f build/reports/jacoco/test/jacocoTestReport.xml
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $files = Get-ChildItem "build/test-results/" -Filter *.xml
      for ($i=0; $i -lt $files.Count; $i++) {
        (New-Object 'System.Net.WebClient').UploadFile($url, $files[$i])
      }
artifacts:
  - path: build/distributions/*.zip
    name: Java archive
