# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Integration tests

on:
  push:
    branches: [ ci_iss680 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit, integration and fixed client tests 
      run: | 
        ./gradlew check
        ./src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh

    - name: Generate test reports and upload them
      run: | 
        ./gradlew jacocoTestReport jacocoIntegrationTestReport jacocoFixedClientEnvironmentTestReport;
        bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
        bash <(curl -s https://codecov.io/bash) -e JDK,OS -F integration -f build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml;
        bash <(curl -s https://codecov.io/bash) -e JDK,OS -F fixedclientenvironment -f build/reports/jacoco/jacocoFixedClientEnvironmentTestReport/jacocoFixedClientEnvironmentTestReport.xml
      env: 
        OS: linux
        JDK: openjdk11

