# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unit tests windows-latest

on:
  push:
    branches: [ ci_iss680 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build on Windows and run unit and live tests

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare test directory
      run: mkdir build\integrationTest

    - run: cd build\integrationTest 
    - run:  ..\..\src\liveTest\resources\scripts\create_symlinks.bat 
    - run: dir
    - run: pwd
    - run: cd ..\..

    - name: Build with Gradle and run unit and live tests
      run: .\gradlew.bat test liveTest "-Dxenon.scheduler=local" "-Dxenon.scheduler.location=D:\a\xenon\xenon" "-Dxenon.filesystem=file" "-Dxenon.filesystem.location=D:\a\xenon\xenon" "-Dxenon.username=xenon" "-Dxenon.filesystem.basedir=\a\xenon\xenon\build\integrationTest" "-Dxenon.separator=\" "-Dxenon.filesystem.expected.workdir=\a\xenon\xenon" "-Dxenon.scheduler.workdir=\a\xenon\xenon" "-Dxenon.scheduler.supportsInteractive=1" "-Dxenon.scheduler.isEmbedded=1"

    - name: Upload test report 
      uses: actions/upload-artifact@v2
      with:
        name: windows-test-report
        path: path/to/artifact/ 
